### ISSUE TITLE
开源了个寂寞

### ISSUE THREAD

**Issue by Luo-Yihong** [karenlatong/AGC-master#2]
training代码写在test里，训练参数写成定值，这开源了个寂寞，不想开源可以不开

**Comment by karenlatong** [comment]
这个模型本身就不是深度模型，并不需要模型参数的训练，算法就是个调整阶数k进行谱聚类的过程。此外这个算法也没什么参数要设置，唯一要设置的就是最大迭代次数。请看明白论文和代码再来评论。

**Comment by Luo-Yihong** [comment]
不是深度模型就不需要划分training和testing了吗？训练集，测试集，验证集，恰恰就是统计学习提出来的。最大迭代数，dataset参数写死在代码里，这就是我说的训练参数写成定值在代码里，这还需要看明白论文和代码吗？开源诚意不足就大大方方承认好吧

**Comment by karenlatong** [comment]
我这是聚类，又不是分类，分什么训练集、测试集和验证集。最大迭代次数和数据集你自己想换就换呗，没看到哪个代码数据集不提前设置好的，你看看GCN的代码是不是也要设置好数据集。

**Comment by Luo-Yihong** [comment]
更换max_iter，dataset参数，起码有个args吧，你这样写还得别人翻进去找，这就是开源诚意不足啊，难道你自己在做实验的时候，每一个参数手动翻到main去修改？这格式给到人的感觉就是随随便便凑合一下，我没说你代码写错了好吧

**Comment by karenlatong** [comment]
你说写args确实是比较规范的写法，这个我承认。后期我写代码也都会加args，这个代码是刚接触python写的代码。

**Comment by karenlatong** [comment]
但是我这个就是为了开源才放出来的，并没有不想开源的意思。

**Comment by Luo-Yihong** [comment]
我其实就是想表达既然开源了，代码组织和写法就规范一点让大家好上手lol。

**Comment by karenlatong** [comment]
OK，误会解除了。

**Comment by Luo-Yihong** [comment]
OK，我开头用词激烈了一点，不好意思，向你表达一下我的歉意

**Comment by karenlatong** [comment]
好的，握手言和了
